name: check-dir-permission

on:
  pull_request:
    types: [opened]

jobs:
  commentSimpleComment:
    runs-on: ubuntu-latest
    name: Creating a simple comment
    steps:
      - name: commeeeeeeent
        uses: ./github-actions/check-dir-permission